<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Labseni</title>
</head>
<body>
	<ul>
		<li><a href="#topik_tutor">Tutorial</a></li>
		<li><a href="#topik_paper">Paper</a></li>
		<li><a href="#topik_magz">Magz</a></li>
	</ul>
<h1>Lalu Bagaimana</h1>
<p>Dalam concerning in tehnologi kesadaran untuk membuat sesuatu.</p>
	<h1><a name="topik_tutor">Tutorial</h1></a>
	<p>SEED merupakan sebuah konsep yang dipaparkan dalam film kartun yang saya tonton 5 tahunan lalu. Dulu aku begitu tertarik mengankat topik ini dan membicarakan dengan orang yang saya temui entah dengan guru kimia, maupun biologi, bahkan topik ini pernah saya bahas dengan Nona Voldemort. Kisah ini menarik perhatian saya karena tokoh Goerge Green, adalah seorang manusia sintesa, dari rangkaian genetika yang terstruktur. Hingga dia menjadi sangat jenius dan mendapatkan gelar Doktor Summa Cumlaude  di MIT pada usia 17 tahun.  Hal ini sangat mencengankan banyak pihak didunia hingga dia berhasil menyelesaikan proyek membangun koloni luar angkasa (Space Colony), sayangnya dia mengalami kecelakaan hingga dia tewas, dalam kejadian tewasnya, dia mengungkapkan bahwa dia adalah seorang manusia sintesa, dimana rangkaian dari genetikanya telah diatur hingga dia bisa melakukan berbagai kegiatan dengan kecerdasan yang beragam, dan mempelajari sesuatu dengan sangat cepat. Kabar ini dipaparkan dalam sebuah black box dalam pesawat sebelum dia menghilang di luar angkasa. Setelah pemaparannya manusia berbondong bondong untuk menciptakan manusia buatan, untuk kehidupan yang lebih baik. Namun kalangan manusia natural (yang tidak tercipta dari proses sintesa) mengalami kecemburuan karena manusia sintesa memiliki kecerdasan yang lebih tinggi dibandingkan dengan manusia biasa. Hal ini membuat perpecahan di dunia hingga, para manusia sintesa melarikan diri untuk menghindari pertikaian dengan pergi keluar angkasa. Gundam SEED eps 14.
Saya benar tidak mengerti mengapa 5 tahun yang lalu aku begitu tertarik dengan rekayasa genetika hingga mencarinya di ocw, atau yang lainnya. Tapi apa daya, kemampuan yang tidak mumpuni ditambah fasilitas yang pas-pasan, saya hanya mampu belajar sedikit tentang bahasa pemrograman, itupun termotivasi karena tokoh utama dalam film tersebut memiliki kemampuan di bidang komputer. Karena keterbatasan ini saya mengurungkan niat dan belajar kembali kemasa-masa manuisa pada umumnya, yaitu belajar dikelas, walaupun dengan kembalinya aku kesana pandangan ku menjadi agak lain karena beragam buku yang saya baca (Elektronika, Pemrograman, Fisika belum filsafat.), walaupun saya tidak mengerti isi yang saya baca.
Pucuk dicinta, ularpun masuk dan keluar didalam. Tak sengaja mengerjakan TA yang terlambat, karena keterbatasan kemampuan otak sendiri, saya mendapatkan topik yang berganti, dalam IEEE, hanya ada 1 topik mengenai bladeRF, yaitu tentang membuat perangkat medis dengan BladeRF. Dan lagi-lagi salah buku, hingga menemukan metode pemrograman biologi, tentang DNA. Dalam buku tersebut secara teknis membahas bagaimana cara kita untuk memprogram rangkaian DNA. Lah kalo begitu jika kita menciptakan sebuah sistem yang seperti dalam film science fiksi tersebut apakah SEED akan terwujud? 
Dengan inputan berupa rantai DNA awal yang muncul dari perpaduan antara sel jantan dan betina akan membuat sel baru dengan rantai DNA yang unik, namun proses perekombinasian DNA tersebut kita kontrol dengan mengatur parameter yang berpengaruh pada rekombinasi DNA (misal dengan suhu, radiasi nuklir atau efek gelombang elektromagnetik). Proses rekombinasi ini akan terus berlangsung hingga menjadi sebuah individu. Sebelum kita menyusun contoller untuk menjaga output, kita harus memetakan dahulu DNA output seperti apa yang kita inginkan. Dengan inferensi data DNA manusia output kita akan mencoba mendesain sebuah kontroller yang akan membuat proses ini sampai pada tujuan yang kita inginkan.	</p>
	<h1><a name="topik_paper">Paper</h1></a>
	<p>SEED merupakan sebuah konsep yang dipaparkan dalam film kartun yang saya tonton 5 tahunan lalu. Dulu aku begitu tertarik mengankat topik ini dan membicarakan dengan orang yang saya temui entah dengan guru kimia, maupun biologi, bahkan topik ini pernah saya bahas dengan Nona Voldemort. Kisah ini menarik perhatian saya karena tokoh Goerge Green, adalah seorang manusia sintesa, dari rangkaian genetika yang terstruktur. Hingga dia menjadi sangat jenius dan mendapatkan gelar Doktor Summa Cumlaude  di MIT pada usia 17 tahun.  Hal ini sangat mencengankan banyak pihak didunia hingga dia berhasil menyelesaikan proyek membangun koloni luar angkasa (Space Colony), sayangnya dia mengalami kecelakaan hingga dia tewas, dalam kejadian tewasnya, dia mengungkapkan bahwa dia adalah seorang manusia sintesa, dimana rangkaian dari genetikanya telah diatur hingga dia bisa melakukan berbagai kegiatan dengan kecerdasan yang beragam, dan mempelajari sesuatu dengan sangat cepat. Kabar ini dipaparkan dalam sebuah black box dalam pesawat sebelum dia menghilang di luar angkasa. Setelah pemaparannya manusia berbondong bondong untuk menciptakan manusia buatan, untuk kehidupan yang lebih baik. Namun kalangan manusia natural (yang tidak tercipta dari proses sintesa) mengalami kecemburuan karena manusia sintesa memiliki kecerdasan yang lebih tinggi dibandingkan dengan manusia biasa. Hal ini membuat perpecahan di dunia hingga, para manusia sintesa melarikan diri untuk menghindari pertikaian dengan pergi keluar angkasa. Gundam SEED eps 14.
Saya benar tidak mengerti mengapa 5 tahun yang lalu aku begitu tertarik dengan rekayasa genetika hingga mencarinya di ocw, atau yang lainnya. Tapi apa daya, kemampuan yang tidak mumpuni ditambah fasilitas yang pas-pasan, saya hanya mampu belajar sedikit tentang bahasa pemrograman, itupun termotivasi karena tokoh utama dalam film tersebut memiliki kemampuan di bidang komputer. Karena keterbatasan ini saya mengurungkan niat dan belajar kembali kemasa-masa manuisa pada umumnya, yaitu belajar dikelas, walaupun dengan kembalinya aku kesana pandangan ku menjadi agak lain karena beragam buku yang saya baca (Elektronika, Pemrograman, Fisika belum filsafat.), walaupun saya tidak mengerti isi yang saya baca.
Pucuk dicinta, ularpun masuk dan keluar didalam. Tak sengaja mengerjakan TA yang terlambat, karena keterbatasan kemampuan otak sendiri, saya mendapatkan topik yang berganti, dalam IEEE, hanya ada 1 topik mengenai bladeRF, yaitu tentang membuat perangkat medis dengan BladeRF. Dan lagi-lagi salah buku, hingga menemukan metode pemrograman biologi, tentang DNA. Dalam buku tersebut secara teknis membahas bagaimana cara kita untuk memprogram rangkaian DNA. Lah kalo begitu jika kita menciptakan sebuah sistem yang seperti dalam film science fiksi tersebut apakah SEED akan terwujud? 
Dengan inputan berupa rantai DNA awal yang muncul dari perpaduan antara sel jantan dan betina akan membuat sel baru dengan rantai DNA yang unik, namun proses perekombinasian DNA tersebut kita kontrol dengan mengatur parameter yang berpengaruh pada rekombinasi DNA (misal dengan suhu, radiasi nuklir atau efek gelombang elektromagnetik). Proses rekombinasi ini akan terus berlangsung hingga menjadi sebuah individu. Sebelum kita menyusun contoller untuk menjaga output, kita harus memetakan dahulu DNA output seperti apa yang kita inginkan. Dengan inferensi data DNA manusia output kita akan mencoba mendesain sebuah kontroller yang akan membuat proses ini sampai pada tujuan yang kita inginkan.
	</p>
	<h1><a name="topik_magz">Magazine</h1></a>
	<p>SEED merupakan sebuah konsep yang dipaparkan dalam film kartun yang saya tonton 5 tahunan lalu. Dulu aku begitu tertarik mengankat topik ini dan membicarakan dengan orang yang saya temui entah dengan guru kimia, maupun biologi, bahkan topik ini pernah saya bahas dengan Nona Voldemort. Kisah ini menarik perhatian saya karena tokoh Goerge Green, adalah seorang manusia sintesa, dari rangkaian genetika yang terstruktur. Hingga dia menjadi sangat jenius dan mendapatkan gelar Doktor Summa Cumlaude  di MIT pada usia 17 tahun.  Hal ini sangat mencengankan banyak pihak didunia hingga dia berhasil menyelesaikan proyek membangun koloni luar angkasa (Space Colony), sayangnya dia mengalami kecelakaan hingga dia tewas, dalam kejadian tewasnya, dia mengungkapkan bahwa dia adalah seorang manusia sintesa, dimana rangkaian dari genetikanya telah diatur hingga dia bisa melakukan berbagai kegiatan dengan kecerdasan yang beragam, dan mempelajari sesuatu dengan sangat cepat. Kabar ini dipaparkan dalam sebuah black box dalam pesawat sebelum dia menghilang di luar angkasa. Setelah pemaparannya manusia berbondong bondong untuk menciptakan manusia buatan, untuk kehidupan yang lebih baik. Namun kalangan manusia natural (yang tidak tercipta dari proses sintesa) mengalami kecemburuan karena manusia sintesa memiliki kecerdasan yang lebih tinggi dibandingkan dengan manusia biasa. Hal ini membuat perpecahan di dunia hingga, para manusia sintesa melarikan diri untuk menghindari pertikaian dengan pergi keluar angkasa. Gundam SEED eps 14.
Saya benar tidak mengerti mengapa 5 tahun yang lalu aku begitu tertarik dengan rekayasa genetika hingga mencarinya di ocw, atau yang lainnya. Tapi apa daya, kemampuan yang tidak mumpuni ditambah fasilitas yang pas-pasan, saya hanya mampu belajar sedikit tentang bahasa pemrograman, itupun termotivasi karena tokoh utama dalam film tersebut memiliki kemampuan di bidang komputer. Karena keterbatasan ini saya mengurungkan niat dan belajar kembali kemasa-masa manuisa pada umumnya, yaitu belajar dikelas, walaupun dengan kembalinya aku kesana pandangan ku menjadi agak lain karena beragam buku yang saya baca (Elektronika, Pemrograman, Fisika belum filsafat.), walaupun saya tidak mengerti isi yang saya baca.
Pucuk dicinta, ularpun masuk dan keluar didalam. Tak sengaja mengerjakan TA yang terlambat, karena keterbatasan kemampuan otak sendiri, saya mendapatkan topik yang berganti, dalam IEEE, hanya ada 1 topik mengenai bladeRF, yaitu tentang membuat perangkat medis dengan BladeRF. Dan lagi-lagi salah buku, hingga menemukan metode pemrograman biologi, tentang DNA. Dalam buku tersebut secara teknis membahas bagaimana cara kita untuk memprogram rangkaian DNA. Lah kalo begitu jika kita menciptakan sebuah sistem yang seperti dalam film science fiksi tersebut apakah SEED akan terwujud? 
Dengan inputan berupa rantai DNA awal yang muncul dari perpaduan antara sel jantan dan betina akan membuat sel baru dengan rantai DNA yang unik, namun proses perekombinasian DNA tersebut kita kontrol dengan mengatur parameter yang berpengaruh pada rekombinasi DNA (misal dengan suhu, radiasi nuklir atau efek gelombang elektromagnetik). Proses rekombinasi ini akan terus berlangsung hingga menjadi sebuah individu. Sebelum kita menyusun contoller untuk menjaga output, kita harus memetakan dahulu DNA output seperti apa yang kita inginkan. Dengan inferensi data DNA manusia output kita akan mencoba mendesain sebuah kontroller yang akan membuat proses ini sampai pada tujuan yang kita inginkan.
	</p>
</body>
</html>
